import { randomUUID } from 'crypto';
import { z } from 'zod';
import type { GraphDB } from '../../graph/db.js';
import { previewParseRules } from './preview-parse-rules.js';
import { provideParseRules } from './provide-parse-rules.js';
import { buildGraph } from './build-graph.js';

const RuleSchema = z.object({
  name: z.string(),
  ruleType: z.enum(['node', 'edge', 'resolve', 'linking', 'doc_link']),
  query: z.string(),
  packName: z.string().optional(),
  nodeType: z.string().optional(),
  edgeType: z.string().optional(),
  nameCapture: z.string().optional(),
  sourceCapture: z.string().optional(),
  targetCapture: z.string().optional(),
  docCapture: z.string().optional(),
  symbolCapture: z.string().optional(),
  priority: z.number().optional(),
});

const QueryPackSchema = z.object({
  name: z.string(),
  packType: z.enum(['comment_doc_linking']),
  rules: z.array(RuleSchema),
});

const ArtifactSchema = z.discriminatedUnion('artifactType', [
  z.object({
    name: z.string(),
    artifactType: z.literal('injection_query'),
    packName: z.string().optional(),
    content: z.string(),
    targetLanguage: z.string().optional(),
    priority: z.number().optional(),
  }),
  z.object({
    name: z.string(),
    artifactType: z.literal('included_ranges'),
    packName: z.string().optional(),
    query: z.string(),
    rangeCapture: z.string().optional(),
    priority: z.number().optional(),
  }),
]);

interface RefineHistoryEntry {
  round: number;
  mode: 'preview' | 'apply';
  queryErrorCount: number;
  applied: boolean;
  indexed: boolean;
  timestamp: number;
  timestampIso?: string;
}

export const schema = {
  stateToken: z.string().optional().describe('Continuation token for a refine session. On follow-up calls, you may send only stateToken plus revised rules/queryPacks.'),
  maxRefineRounds: z.number().int().min(1).max(5).optional().describe('Start a server-side refine session and return a state token for up to N follow-up preview/apply rounds'),
  rootPath: z.string().optional().describe('Absolute project root used for previewing rules before apply'),
  language: z.string().optional().describe('Target language, e.g. "typescript", "python". Must be a supported Tree-sitter grammar for live preview.'),
  mode: z.enum(['preview', 'apply']).optional().describe('Preview only, or preview then persist rules when valid'),
  filePaths: z.array(z.string()).optional().describe('Optional files to preview before apply'),
  limit: z.number().int().min(1).max(20).default(3).describe('How many files to preview when filePaths is omitted'),
  onlyRuleMatches: z.boolean().optional().describe('If true, preview only doc sections generated by rule packs'),
  matchDetails: z.boolean().optional().describe('If true, include raw query capture details'),
  replace: z.boolean().optional().describe('If true, replace existing stored parse rules for this language on apply'),
  allowApplyWithErrors: z.boolean().optional().describe('If true, persist rules even when preview reports queryErrors'),
  applyIndex: z.boolean().optional().describe('If true, trigger build_graph after rules are successfully applied'),
  includeDocs: z.boolean().optional().describe('Used with applyIndex. Also index Markdown docs (default true)'),
  delta: z.boolean().optional().describe('Used with applyIndex. Only re-index changed files (default true)'),
  rules: z.array(RuleSchema).optional().describe('Direct parse rules'),
  queryPacks: z.array(QueryPackSchema).optional().describe('Named query packs'),
  artifacts: z.array(ArtifactSchema).optional().describe('First-class artifacts such as injections.scm content and included range selectors'),
};

/**
 * MCP Tool Handler.
 * @param db The GraphDB core reference
 * @param args Tool specific schema arguments
 * @returns The queried internal schema nodes or operation results for the Agent
 */
export async function previewApplyParseRules(
  db: GraphDB,
  args: {
    stateToken?: string;
    maxRefineRounds?: number;
    rootPath?: string;
    language?: string;
    mode?: 'preview' | 'apply';
    filePaths?: string[];
    limit?: number;
    onlyRuleMatches?: boolean;
    matchDetails?: boolean;
    replace?: boolean;
    allowApplyWithErrors?: boolean;
    applyIndex?: boolean;
    includeDocs?: boolean;
    delta?: boolean;
    rules?: z.infer<typeof RuleSchema>[];
    queryPacks?: z.infer<typeof QueryPackSchema>[];
    artifacts?: z.infer<typeof ArtifactSchema>[];
  },
) {
  const session = args.stateToken ? db.getRefineSession(args.stateToken) : null;
  if (args.stateToken && !session) {
    return { ok: false, error: `Unknown stateToken: ${args.stateToken}` };
  }

  const resolved = {
    rootPath: args.rootPath ?? (session?.payload['rootPath'] as string | undefined),
    language: args.language ?? (session?.payload['language'] as string | undefined),
    mode: args.mode ?? (session?.payload['mode'] as 'preview' | 'apply' | undefined) ?? 'preview',
    filePaths: args.filePaths ?? (session?.payload['filePaths'] as string[] | undefined),
    limit: args.limit ?? (session?.payload['limit'] as number | undefined),
    onlyRuleMatches: args.onlyRuleMatches ?? (session?.payload['onlyRuleMatches'] as boolean | undefined) ?? true,
    matchDetails: args.matchDetails ?? (session?.payload['matchDetails'] as boolean | undefined) ?? true,
    replace: args.replace ?? (session?.payload['replace'] as boolean | undefined),
    allowApplyWithErrors: args.allowApplyWithErrors ?? (session?.payload['allowApplyWithErrors'] as boolean | undefined),
    applyIndex: args.applyIndex ?? (session?.payload['applyIndex'] as boolean | undefined),
    includeDocs: args.includeDocs ?? (session?.payload['includeDocs'] as boolean | undefined),
    delta: args.delta ?? (session?.payload['delta'] as boolean | undefined),
  };

  if (!resolved.rootPath || !resolved.language) {
    return { ok: false, error: 'rootPath and language are required unless supplied by stateToken' };
  }

  const preview = await previewParseRules(db, {
    rootPath: resolved.rootPath,
    language: resolved.language,
    filePaths: resolved.filePaths,
    limit: resolved.limit,
    onlyRuleMatches: resolved.onlyRuleMatches,
    matchDetails: resolved.matchDetails,
    rules: args.rules,
    queryPacks: args.queryPacks,
    artifacts: args.artifacts ?? (session?.payload['artifacts'] as z.infer<typeof ArtifactSchema>[] | undefined),
  });

  if (!preview.ok) return { ok: false as const, error: preview.error };

  const queryErrorCount = (preview.previews as Array<{ queryErrors?: unknown[] }>).reduce(
    (sum, filePreview) => sum + (filePreview.queryErrors?.length ?? 0),
    0,
  );

  const currentHistory = Array.isArray(session?.payload['history'])
    ? normalizeHistory(session?.payload['history'] as RefineHistoryEntry[])
    : [];
  let responseHistory = currentHistory;

  let nextState: { stateToken: string; roundsRemaining: number; maxRefineRounds?: number } | undefined;
  const requestedRounds = args.maxRefineRounds ?? (session?.payload['maxRefineRounds'] as number | undefined);
  if (requestedRounds && !args.stateToken) {
    const token = randomUUID();
    db.upsertRefineSession(token, {
      rootPath: resolved.rootPath,
      language: resolved.language,
      mode: resolved.mode,
      filePaths: resolved.filePaths,
      limit: resolved.limit,
      onlyRuleMatches: resolved.onlyRuleMatches,
      matchDetails: resolved.matchDetails,
      replace: resolved.replace,
      allowApplyWithErrors: resolved.allowApplyWithErrors,
      applyIndex: resolved.applyIndex,
      includeDocs: resolved.includeDocs,
      delta: resolved.delta,
      maxRefineRounds: requestedRounds,
      artifacts: args.artifacts,
      history: [],
    }, requestedRounds);
    nextState = { stateToken: token, roundsRemaining: requestedRounds, maxRefineRounds: requestedRounds };
  }

  if (session) {
    if (session.roundsRemaining <= 0) {
      db.deleteRefineSession(session.token);
      return {
        ok: false,
        mode: resolved.mode,
        applied: false,
        blockedByMaxRefineRounds: true,
        preview,
      };
    }
    const remaining = session.roundsRemaining - 1;
    responseHistory = appendHistory(currentHistory, {
      round: currentHistory.length + 1,
      mode: resolved.mode,
      queryErrorCount,
      applied: false,
      indexed: false,
      timestamp: Date.now(),
      timestampIso: new Date().toISOString(),
    });
    db.upsertRefineSession(session.token, {
      ...session.payload,
      history: responseHistory,
    }, remaining);
    nextState = { stateToken: session.token, roundsRemaining: remaining, maxRefineRounds: session.payload['maxRefineRounds'] as number | undefined };
  }

  if (resolved.mode === 'preview') {
    return {
      ok: true,
      mode: 'preview',
      applied: false,
      queryErrorCount,
      preview,
      refineState: nextState,
      sessionSummary: makeSessionSummary(responseHistory),
      history: responseHistory,
    };
  }

  if (queryErrorCount > 0 && !resolved.allowApplyWithErrors) {
    return {
      ok: false,
      mode: 'apply',
      applied: false,
      blockedByQueryErrors: true,
      queryErrorCount,
      preview,
      refineState: nextState,
      sessionSummary: makeSessionSummary(responseHistory),
      history: responseHistory,
    };
  }

  const applied = provideParseRules(db, {
    language: resolved.language,
    rules: args.rules,
    queryPacks: args.queryPacks,
    artifacts: args.artifacts ?? (session?.payload['artifacts'] as z.infer<typeof ArtifactSchema>[] | undefined),
    replace: resolved.replace,
  });

  const indexSummary = resolved.applyIndex
    ? await buildGraph(db, {
        rootPath: resolved.rootPath,
        delta: resolved.delta ?? true,
        includeDocs: resolved.includeDocs ?? true,
      })
    : undefined;

  if (session) db.deleteRefineSession(session.token);

  const finalHistory = appendHistory(currentHistory, {
    round: currentHistory.length + 1,
    mode: resolved.mode,
    queryErrorCount,
    applied: true,
    indexed: !!resolved.applyIndex,
    timestamp: Date.now(),
    timestampIso: new Date().toISOString(),
  });

  return {
    ok: true,
    mode: 'apply',
    applied: true,
    indexed: !!resolved.applyIndex,
    queryErrorCount,
    preview,
    appliedRules: applied,
    indexSummary,
    refineState: session ? { stateToken: session.token, roundsRemaining: 0, completed: true } : nextState,
    sessionSummary: makeSessionSummary(finalHistory),
    history: finalHistory,
  };
}

/**
 * Auto-documented structural element.
 */
function appendHistory(history: RefineHistoryEntry[], entry: RefineHistoryEntry): RefineHistoryEntry[] {
  return [...history, entry].slice(-10);
}

/**
 * Auto-documented structural element.
 */
function normalizeHistory(history: RefineHistoryEntry[]): RefineHistoryEntry[] {
  return history.map((entry) => ({
    ...entry,
    timestampIso: entry.timestampIso ?? new Date(entry.timestamp).toISOString(),
  }));
}

/**
 * Auto-documented structural element.
 */
function makeSessionSummary(history: RefineHistoryEntry[]) {
  const rounds = history.length;
  const previews = history.filter((item) => item.mode === 'preview').length;
  const applies = history.filter((item) => item.mode === 'apply').length;
  const last = history.at(-1);
  const totalQueryErrors = history.reduce((sum, item) => sum + item.queryErrorCount, 0);
  return {
    rounds,
    previews,
    applies,
    totalQueryErrors,
    lastMode: last?.mode,
    lastApplied: last?.applied ?? false,
    lastIndexed: last?.indexed ?? false,
  };
}
